"""多用户系统：users 表 + user_id 外键

Revision ID: 239a2fd3a3e8
Revises: 2b7b725a5ba5
Create Date: 2026-07-08 20:52:41.176556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239a2fd3a3e8'
down_revision = '2b7b725a5ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing = inspector.get_table_names()

    if 'users' not in existing:
        op.create_table('users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('username', sa.String(length=50), nullable=False),
            sa.Column('email', sa.String(length=120), nullable=False),
            sa.Column('password_hash', sa.String(length=256), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('session_token', sa.String(length=64), nullable=True),
            sa.Column('last_login', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('email'),
            sa.UniqueConstraint('username'),
        )

    with op.batch_alter_table('categories', schema=None) as batch_op:
        if 'user_id' not in [c['name'] for c in inspector.get_columns('categories')]:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
            batch_op.create_foreign_key('fk_categories_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        if 'user_id' not in [c['name'] for c in inspector.get_columns('notifications')]:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
            batch_op.create_foreign_key('fk_notifications_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        if 'user_id' not in [c['name'] for c in inspector.get_columns('tasks')]:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
            batch_op.create_foreign_key('fk_tasks_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categories_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('users')
    # ### end Alembic commands ###
